#!/usr/bin/python

import argparse
import subprocess

parser = argparse.ArgumentParser(description='Phono configuration')
parser.add_argument('--password',
                    default='admin',
                    dest='nginx_password',
                    help='Nginx login password')
parser.add_argument('--hostname',
                    default='localhost',
                    dest='nginx_hostname',
                    help='Hostname used for Nginx\'s SSL certificate')
args = parser.parse_args()


def replace(key, value, file):
    cmd = 'sed --in-place="" "s:<{0}>:{1}:g" {2}'.format(key, value, file)
    subprocess.call(cmd, shell=True)


def encrypt_password(password):
    return subprocess.check_output('openssl passwd {0}'.format(password),
                                   shell=True).rstrip()


def generate_ssl_cert(hostname):
    keyout = '/etc/nginx/ssl/key.pem'
    certout = '/etc/nginx/ssl/cert.pem'
    cmd = 'openssl req -x509 -nodes -newkey rsa:2048 -keyout {0} -out {1} -days 3560 -subj "/CN={2}"'.format(
        keyout, certout, hostname)
    subprocess.call(cmd, shell=True)


generate_ssl_cert(args.nginx_hostname)

replace('password', encrypt_password(args.nginx_password),
        '/etc/nginx/conf.d/htpasswd')

subprocess.call(['/usr/bin/supervisord', '-c',
                 '/etc/supervisor/conf.d/supervisord.conf'])
